[build]
  command = "echo 'No build required for serverless functions'"
  publish = "."
  functions = "netlify/functions"

[dev]
  framework = "#static"
  functionsPort = 8888
  targetPort = 8888

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@pinata/sdk"]
  included_files = ["lib/banned-words.js"]

